version: "3.10"

services:
  burger95s-backend:
    image: burger95s:V2
    ports:
      - 9999:9999
    volumes:
      - ./myvol:/myvol
    depends_on:
      - burger95s-db
  burger95s-db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - .data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=210497
      - POSTGRES_USER=postgres
    restart: always
